<?php  //[STAMP] dfe35e8341c5487be73cafcb7ef0d497
namespace Forge\App\Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
